# Generated by Django 4.2.10 on 2024-03-06 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atende',
            options={'verbose_name': 'Médico Convênio', 'verbose_name_plural': 'Médico Convênios'},
        ),
    ]
